apiVersion: v1
kind: Secret
metadata:
    name: test-secret
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:UQrAlvWhgWkgogaBkZkQnYUDSCUs8S+IWg==,iv:0FS5lUOA1Qym/ZXyGQXo1KSUd2TEKEG8bQpaXvlmleQ=,tag:y7KkgbJu5ey3jqOFWg6xXg==,type:str]
sops:
    age:
        - recipient: age10mnx9lzy5ls2zl09qpsr4zryf9lys2qnv3a55832m436fzc0933q3sfn2t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNTZsQXhOSG5TMHNvaUUx
            RjlNeUk3eU8wTWQvNVB2NHBZUytZRCtsbkd3CnplSlVYS2d3V2lKOUNTbW9kblp3
            WisvREs0UVFHSWd6b0lFSGZkRFY3dlkKLS0tIGRIbkt3M1dJZk9Wend6QXFieUNj
            THZGVGEwTXFZVTRGVm40ckhsd0UwREEKP9xT731b92KoRff0fWZKeK8AtltquVlU
            0P+wBF2tCYFLs3b5ifrcGq9tiydrdgAwq3BSGP9GbKr0C+LyieohlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T02:59:30Z"
    mac: ENC[AES256_GCM,data:0SmPjHiZ4S0eFPYiNKozMti0T1wdUZzLDYMoenWhkveAUsbGVZkMhW4Rq37SFnRV3ztCJKIhRAq9zKucDbXYlb6o4oSKZ1IZVlJNrMbLEEsoe+PYR147QQVtYhPnipAYD1wp01cYD0kK1sU3y8FbQyNF68KQ6Lcr+P7nyzwhXCQ=,iv:nVS3GIwOFS6pAUZIkUN4HcC2CUUvjTY2ld3aIEwIETI=,tag:aJhg+HrfEqonsgzyrZ2lAw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
