apiVersion: v1
kind: Secret
metadata:
    name: test-secret
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:dJUSbp1nML9GUXAgthx0zOlDyuWyjTzMnQ==,iv:vcPBMOd006yNy+xRjzC9c0dI9pOcyrNgd/nPlV++pDo=,tag:Q5WdZvqTWvRhZx9v7/fExA==,type:str]
sops:
    age:
        - recipient: age1y4x8gzzcdhxvqaf9matt0eze3z3yxwx607avq4cexfkgwal4psesj39lvn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSzVhOEZiVG1Eek9QaFVv
            UG55VkI5NnpKVWV1b0k4WkRVUkhTblRVdFVzCmprNEUrTmg4UEpZeERLeStTWG9k
            aHBuSmN3SllyV1o4bmxwRmF1VU5EaEEKLS0tIEM5SDNQTTRHaW1tenhZM3dYQmNq
            TWZhRmhEb0VIdW9hSVJRL2UxNkM0RkkKD2vSu9Q78JyoKkS5ALM7JtaYvJywsqfo
            64wVS1ILSlDlQmwkJvAqyKwrC7G+mA7rVxZV0EOSZPwm20a6fAg2kQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10mnx9lzy5ls2zl09qpsr4zryf9lys2qnv3a55832m436fzc0933q3sfn2t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UGlBNk01bGlReEU3WUZm
            WGpNcjZFQm1DYXphbm5WYU5pMGFlMlk2SlZFCkJ2MUQ5bmN3bXBBeUFXdlZ3aFNo
            OGFqUXhMLzFlKzJiWElYRWx0VnF3blEKLS0tIEdtN0h4Q0VvL1Q3NlNidGxkcXlR
            OFM1ME1wNmtWd2d4czh2bmRJSHcrZzgKvv3CEcDsD/UaouOmfXaiGUSz7T98IdOQ
            jSh3yAu/X9rA6Yg9yXwJ7vesfqQdG+kSgX7pQL40cNTQp1WUTXbK0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T03:46:03Z"
    mac: ENC[AES256_GCM,data:x+xlO4auPonr10B3B+gEViW2TQLhdevEjlEsnwwj99TtRvLfHLGS0cF0c7m6WDZurAAzH2TOtXuL2HuIw9y10fDey1hTzxvnw214cBweVOJRXBUummLVVu1vW8Mw2BINyAU8BxaVCD+03+NQWF2iGmS3KbBIBtRbUfjCl+PhUoc=,iv:E3XEb0hQWGfdcNKVRS4C6+XcKCf/8/+tL295wXHbgWQ=,tag:5bwXFWHu669kcMbCS6F69w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
