apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openbao
  namespace: openbao
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`openbao.traefik.soriphoono.com`)
      kind: Rule
      services:
        - name: openbao
          port: 8200
