apiVersion: ENC[AES256_GCM,data:fUnwOCU0+BU=,iv:3dP5WH9z6GynlH0gE/F/pD7qOPy1aPZvMiKQr/HEhpE=,tag:ovqHmtCmQpLA2FmRu0WdFg==,type:str]
kind: ENC[AES256_GCM,data:o4MuKtQzXi0EDu3LuCMj/XCJs2xg6A==,iv:nEWhrxPM9y4nsymBi8N2xXtPRg00qc9t98SvB1w+jMk=,tag:gLMtWtscurEsE73gcnwxeg==,type:str]
name: ENC[AES256_GCM,data:KuEwCaNSabI5,iv:w5D2qy/A4LlTqoWcWwMW2tFnCs9K1WkZ9LkFxwadEHA=,tag:uW3NuKw7KwnRS5xjJSkRWg==,type:str]
environment:
    - ENC[AES256_GCM,data:6ccokC5G2Xgsj9+/xXlZWN0GPAGd5L7XFoOml8jRqSwKqk3Zb7A7yHWBAYe6AqrZP0l255jwkx6PoAsyv5IMNfwJSGuv5EYA,iv:p637XyGvRBvcgapa66LN3zz3BfmKYe9apsbfi6NS1lc=,tag:YyVkQN16ksOdYFa2sPgVUw==,type:str]
sops:
    age:
        - recipient: age1y4x8gzzcdhxvqaf9matt0eze3z3yxwx607avq4cexfkgwal4psesj39lvn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ODJmUllHbWJuNGw5Y1ZO
            VWxRaXRENXlYOW45ayt5aTFuSFgyTlhGUkVrCm8wRnR1S29MNzJCaXJrc3JHR3V4
            dDV4M3pLOVhPS3ZnSTArbEFTdTVBenMKLS0tIEg4blJaMEowbHNwRmtFb3FrYndL
            SVRMKzNqMGpaWFI5M0xkdEdSY0hWdm8KMktZrMQoWjaHssj0QrSKlDTI/ip9yX34
            Q1iDUy8KmdqWrwlZtLBbtMqZDorJUE0me0wnO2oZ7yYDQ0FtrqJOUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T13:30:06Z"
    mac: ENC[AES256_GCM,data:yrBgH95GwcYXZexzmNT4F3Z55boN5vJxNH6Dk/rhzQqNNj/YMrflKs5c+i4JMh8O9WPQJZQeUmuDMgReiM2sCBv1mWt4oOEq6VVuE6iVzquolIWZk/GsW85vF9SMPAE3JCxG58N6yF/jeVczaQS19fzT4Wdpqdst65r1A7uEsxI=,iv:+pwWtaWwL4yycD73n8DF1MjaNpTP1eRf061WNEMV558=,tag:gUKJP4zCPbvWewzoRrQDDA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
