apiVersion: v1
kind: Secret
metadata:
    name: tunnel-token
    namespace: cloudflare-tunnel
stringData:
    #ENC[AES256_GCM,data:rq0TJ1BpkbbxdcZhyCe/bv10oLbefbpLETuEEndmr8r3l33M,iv:m7nmu5StZhfWpHQv/IECfWNgUn0pgYbG5JxvCKiYHwc=,tag:+ajVD63QCaUUc3TMyRrjDg==,type:comment]
    #ENC[AES256_GCM,data:nWDC6m/Dsl2O27Enci+xqxMJK5O5GGHyoY1I8y5p7zaS+BpQJ2muAydKSkwwT1sghL/AS/HGmuR3GZlLPSiW+ZrdEfs=,iv:0VqyqxWIslrnRP35wSVOhRqno5hnM27QUgk5I1k4kjM=,tag:LPoRKyVqlQLzYZGUNCN9hQ==,type:comment]
    #ENC[AES256_GCM,data:uIZ0D1lUBiXfyHzJLkribW1NWmQNE1lGiO1hqfq6lqLzqHEXasLx1KR3COSyUNrZOcR9JIqv+2VKbzTT,iv:Rp0G35gDcuMTjqwobpbluUxcSITDdzzgQVp+RM1XiHw=,tag:Zml5Zo1ycxCD8vujxDMo4g==,type:comment]
    token: ENC[AES256_GCM,data:b6puS0oJos8MYibzuChJTSN4kzuLo3nJzDjnFHdFvEm4QjaxBC8rjwfD0h3CveefJxb+SwiRRu/oGrUT/n2qFSntnQ4SuSHOITZZCwC9pfAAkUJPTt7coOwsZqMidssKMjBsOyWGGaN8YTbUTpjsQ3SzqITUQf1QuFiHUROEv6aBiyG26RAs5lm5xDhju1QT7bfub2I+n9SQMiPXbZDwNZ9tYj7fQgnMuatvRCSu5lq0A9p9Z7E60A==,iv:+8mBTc8q43Uy8rZ6XbI/liOD02HtLbBX1DkI9kqxQtI=,tag:OF6EBE99qLdnbIMTe0Ujsg==,type:str]
sops:
    age:
        - recipient: age1y4x8gzzcdhxvqaf9matt0eze3z3yxwx607avq4cexfkgwal4psesj39lvn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURW0zcmxaTnM4cmtCT2dk
            c21jZk9SMUZHb1I1SHFXVjdkNUZudVB5UGlZCjc4QlhTNnlzQWJCNVhjYTV6Y2dD
            TU05Y2d5N0pXT3JGcnk5a1lsR055S1EKLS0tIEFSK1VTVDY4TFRPMElhTnVnbmVq
            bGNiTXo5QURadkhEVW1aU0ZTZTdRdnMK9wwnG2Q3ahiCSD+Cf23eW2pjIUQKXuHc
            HHwbweRCrklnsIE0IEvuztWZEsCLwsNIpITEB5gvXl3Gb9tG2QZIAw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10mnx9lzy5ls2zl09qpsr4zryf9lys2qnv3a55832m436fzc0933q3sfn2t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNUdTd2RVd0hxdEc3M1N5
            U3d5OFB3alc5bHp6dXRPRXhPVFUwNlhRVHdJCkVkc0xBQkw2bkYxc08vT1pRUXBV
            MTlNTzAxcXZCdTRFR1JQcElMY1lwaTQKLS0tIFB1cTNFR1RkM2NqMkdpSzhpdUxV
            MlpjeW80eXNoZmQ3UWd1K2F6anp0V2cKM6KqKY0pf92JAIuGWSy13k5EUe/LrbXK
            GK4L9CbsZXxgi5p2COAveFhrm+jc0smlKQaQpZrV2F5XTNz6LlSxbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T15:03:12Z"
    mac: ENC[AES256_GCM,data:m5vFVptQbi1FadQXjtfNYeUwHl37llswgeTCDpnuaE3Vk8ITt16eTs2yppLNeWusu1/pVHnYV6lSeg2PDhOMV9GmQ2mVFvNsPVF/vXLQcztZ+m8BPPVNHxijC/SUZh6/7uEQZSn64wPwv5KxYSoDKAKGuAx5QEryEH9Lzbd32Q4=,iv:JxHZHQZexktUgGZU9obU57voLP/JIQYt70aJELu9c7M=,tag:fyYhZFaZSLECx1oFzvybKg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
