apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: adams-apps
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-sources
  interval: 1h
  path: ./k8s/apps/adams
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
