apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 5m
  chart:
    spec:
      chart: tailscale-operator
      version: "1.74.0"
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
      interval: 1m
  values:
    operatorConfig:
      logging: info
      oauth:
        secretRef:
          name: operator-oauth
          key: client_id
          secretKey: client_secret
