apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:+jj3RPmUmx0G5gCgWkDpiX8=,iv:+nr1+75mpZB78qB1b8JN95DF6mYPF8zAgYc17aMOuks=,tag:G/72POH2/R7YIDEdKShQbg==,type:str]
    client_secret: ENC[AES256_GCM,data:SxSIZLzQGOkzH1ohSeqx+adrQa1vykBWAAu2JbWmNWKpaqZ2kTf8od5dSsQA5zZilkAwbLBm0hmPMdU2e3O4Qw==,iv:akVYqgGmOFNvLI4ZjbXtLD4svm0A7cOTudC1qBgjl8E=,tag:YpzJmDSbbcBxt8cdHLQMqQ==,type:str]
sops:
    age:
        - recipient: age1y4x8gzzcdhxvqaf9matt0eze3z3yxwx607avq4cexfkgwal4psesj39lvn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Zk5BVVN6bjZJSEhvRXEy
            RmdxcHNnNEszOWUvYzNEMlhSRmtUMXVMQjNvClpXYmFIKzFQTGMvY1J1Z3c1SHZQ
            eVI4WmF3ODJsTDIwd0dxZTFockN0bFUKLS0tIFJzTTFpUk1ZdVkrQ0krSGptNjRR
            R0xGSis3UW0xOFd2NFlKYkJSaGFJb1kK42WoKSMG4UwOb4sjStuvnpnQ7jIpquzd
            tCWeLsvUBMRPXecq8kPuzonxsVVoz2p58nf4HZVDG1k3PngQBfHHuA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10mnx9lzy5ls2zl09qpsr4zryf9lys2qnv3a55832m436fzc0933q3sfn2t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIY1I2eVhneXdpSzR6ak0x
            OUFKaHdOVzZTT3J3bG1SOVVyTFJnbDB1UVVRCkZHZXNQemtReVQ0T2UvOGNrV1Ez
            M053Szlwc0xKdjJGMlJLNDBDTDlaeDAKLS0tIE9jYk8vL005STBLZVo0U3IwTGR5
            K2xYS2xZKzVmcUpkdi9PMzlFMElQUzAKJ51vC7edx+JOwmBaqn2PJnZzp2E5iXzH
            XsZKftIulGp/gfE+6d4PODnmzHC2JuWM+3sRFOAAbZZYH4REXSRuOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T02:24:52Z"
    mac: ENC[AES256_GCM,data:q8podbys0aE7xU4THri00if0NNI+0Y5yiWIbagTboeS+dl1MZ+KdqtXD2LEeyyD5PO2Y72zywcYI2wxM8JbMhZvgTlTsUEOZuVOp3AnM7NFIyr39Tpk1+7YLHgKHo1rL7bXUX5JIg7MCs9/BeMbSUa2r5v0hpRIjy4aechZDjO8=,iv:dklac/EpSxroFiArlGYNQkcf8CgMWTY5e8J7pJcJuj0=,tag:KcfKBvn9Ez2wQ6zYjoRmHQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
