apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  dependsOn:
    - name: rook-ceph
      namespace: rook-ceph
  interval: 1h
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.19.2
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
  values:
    storageClass:
      blockPool:
        spec:
          replicated:
            size: 1
          failureDomain: osd
    operatorNamespace: rook-ceph
    configOverride: |
      [global]
      osd_pool_default_size = 1
    cephImage:
      repository: quay.io/ceph/ceph
      tag: v19.2.0
    cephClusterSpec:
      dataDirHostPath: /var/lib/rook
      hostNetwork: true
      mon:
        count: 1
        allowMultiplePerNode: true
      mgr:
        count: 1
      placement:
        all:
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
      dashboard:
        enabled: true
      storage:
        useAllNodes: true
        useAllDevices: true
        config:
          databaseSizeMB: "1024"
          journalSizeMB: "1024"
    ingress:
      dashboard: {} # Configure later if needed
