apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-email
    namespace: cert-manager
type: Opaque
stringData:
    email: ENC[AES256_GCM,data:LMlPvx6JMK7fooBfC4dG38NURnA=,iv:/a9AgVA0k+GGNLwVw9s3h8zcrUuzAIVFoFjiUGHh4NA=,tag:knNKNRGeqTRoXuR+ziDSIg==,type:str]
sops:
    age:
        - recipient: age1y4x8gzzcdhxvqaf9matt0eze3z3yxwx607avq4cexfkgwal4psesj39lvn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZ1lLVEVJTmY5Z2lPTXZO
            dXNqekZGMWdIRkZFQytYSmt6RzYvZ1A4aVE0Cm4ycHRzSC9aT2UzVW44WE1MSGlX
            MXIvcUlPdSt1dks2VFJKWHpBb1BGTE0KLS0tIGF4MVdrWVU0TnNNbGFhMzJ3b0w3
            bzI5UGxRUkFGVVlDdDUwOGZnWmVmRUkKQc58ZRtClE9747wgHsJVFzDffpXqv+qe
            /AXZp8TvMH4USfJDNkv7nZAKCItO98tALy+Met2fhoKwEzxaY+q88g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10mnx9lzy5ls2zl09qpsr4zryf9lys2qnv3a55832m436fzc0933q3sfn2t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUDlBVnhFNjBXSSt0SW4z
            MGhSbW44UnJ3cGxjalRUUjRkVm1rRk14Tkc0CmgzTkpIcStuKzhHYWtWaFN6TXNs
            Y1NPSzR1R3h2bE9oVUFDaEt2RlVaRW8KLS0tIFZBTmlLZ3V3Wk81SmYvUTVCZmp2
            cmJlVEtYeTl6Ym8vZlFYQXFmd1ZmQUkKYwPmJSG8homL1vfC4+75CUZI4RZNwJC1
            ExWs6Vhs1fXUDlM1Xk8ASdPiFrEmNN2z0MmLNlCyhO3BagalpMszAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T01:17:09Z"
    mac: ENC[AES256_GCM,data:fJUcF29D8RCWW3hGeEonT+eC6Q7Ng+FADfbmVmQ4/XKfhVw2NhbOP46klmUl2OB7BdknvIGR92QI4VvS6tkAVuMdHig2eXen6ScQ2DJRCRP22axVn2ne8096PqQaQvLeC8UR7fNY+L1TbqSrleQWO+YnD/SFKSX9LRyP3uVLnao=,iv:YbRLR7WRGylYKBNCojBvbufaDztBeqt+k3qHN0cQGXo=,tag:/hFJ28VTEjYpGIjDTOXO6A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
