apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: external-dns
stringData:
    #ENC[AES256_GCM,data:JO2by0Z560BthRi/rINL/z9JRRURLJtcCaG7y1Y8DKKoqvay,iv:mNjAK4vJivdUvnj1j9IYl6LHKuaT38RQnPU4u5NUrEo=,tag:g6yWXNHzbL25XfRdPQ62Ng==,type:comment]
    #ENC[AES256_GCM,data:C/AKglRVC2NKemguVeCQK7UJE+yVBwiQICprFqs5DWCqRn3mqBJRQzIVW6h4sHwr70qvhHTUN1CpJRX3gIuiMJk=,iv:n1C00sg7Pqi477CC2hJSaaTGMryQ9iA1wysGjb/6VwU=,tag:7T6xS8FAnwI7MxATg6gFlQ==,type:comment]
    #ENC[AES256_GCM,data:UvyJ6tnaxVSJ4/aBvCuChCMydUN+VE1hxAbpfsvoZa6id81kxt+CPE8jgovz6jpuHKzSECqrnA==,iv:3Odb7NlZCvEjlpMGlSJQuPiJ7Y6AWMhRF7fM/6O1vsE=,tag:JJuXDnxqi010dYaArXrzBw==,type:comment]
    token: ENC[AES256_GCM,data:XmhL2YRRsQvuQ0q9+aUa6ij0Osw0s6OuCXJqmNjY7187dqYg6C0AuA==,iv:XKVMUx3VqU+J7ZtZ4Mw1iy+hmLTD8UmqkL96gBDs+Uc=,tag:npZ8INtwmOyotyz6l6AINA==,type:str]
sops:
    age:
        - recipient: age1y4x8gzzcdhxvqaf9matt0eze3z3yxwx607avq4cexfkgwal4psesj39lvn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MEdtOTFkMHRuRTNjM3RF
            VlRZTG9oVDZOVDJVRjVxRU43Rk9Rdkp0MXcwCm10bWxSc0pQTjR1bjdOMXUwRElB
            N1ljdVdGa01xdjN6aTdXQmRoMkVReGsKLS0tIHdIb2lxSHduanNRenB0d3dzZmQ2
            RkpBdTBBQzVXUEFBc1NoeGtNOStHY00K7MaZTZ4IwKxzWkST0NkXeH0tGNjBrFLT
            wRARVF6sAlUQ6FEgdfzycC3PLAnGzuJSGua/D33VXXVzqx71xiKPVg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10mnx9lzy5ls2zl09qpsr4zryf9lys2qnv3a55832m436fzc0933q3sfn2t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaE5jeFZ0VDQveFcxeTVR
            MVBkeUd0YjcvcEE2bmd5d0dkZlBGelFMdWs0CjViUnk1U0gyaGpucklneU02cmlK
            SVNwR1UzMWUyN2daRFFBNXB6bGtOdUEKLS0tIEVndDZwR1BnRTZILzF2aDQ4WkFO
            M2k4STI0amppQlEvZ1cxUjRESVpvamcKIgggJ5SutGlOK4COAbYQfafC5jD+2Wyr
            Qf09uVzvgtUdg4VSTyyA1nmKT2YAcx0pk+usYLand1sA7hyDGViF4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T14:57:10Z"
    mac: ENC[AES256_GCM,data:pLdB/RKumd6h9gKNlQLCxQC9S2q0gLRAdPyqX0Cu9Z79jYsck2q2O5lLO+JNvS4HhNcOLl6S5jAGLJVB3QrNPd+3/A3XsupkOgw2iub+iTLpjtjiqI/5BAZNX21/0AhMNow/ah02bIZOiuZCYS8DAnR0K2Q9/6uIWTo27wVkQQ8=,iv:/DGoGqz1L5stjPr23r9FpYThopfBZaVN9bVk0t8VKy4=,tag:EgSTQkXz1wAHK2lSQAEYkQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
